@startuml

header Диаграмма последовательностей для демона STP
footer Page %page% of %lastpage%

skinparam shadowing<<no_shadow>> false
skinparam shadowing<<with_shadow>> true
skinparam sequenceMessageAlign direction

skinparam ParticipantPadding 12
skinparam BoxPadding 15

skinparam defaultFontSize 16
skinparam defaultFontName Aapex

participant "STP daemon+\rRDP_translator" as Daemon #99FF99
box "Linux" #LightBlue
queue "Kernel" as Kernel #006fdf
collections "NETLINK_IF" as Netlink #dfa800
end box
box "RDPD" #BlanchedAlmond
control "RDP_STPMANAGER" as RDPD #bc78ff
boundary "ASICd" as ASIC #b4506e
end box

[o-> Daemon : Запуск демона

Daemon /[#green]- Daemon : Инициализация
Daemon -[#purple]> RDPD : Оповещение [STPd_Cold_Start]
' RDPD <-[#b4506e]> ASIC : Sync \n[asic_state_v]
Daemon -[#green]/ Daemon : Ожидание конфигурации

group#Gold Цикл конфигурационный
    RDPD -[#purple]> Daemon : Установка конфигурации [RDPD config msg]
    Daemon -[#purple]> RDPD : Response [RDPD config msg]
    Netlink --[#df7000]> Daemon : Получение всех актуальных интерфейсов системы
    RDPD -[#purple]-> Daemon : Обновление конфигурации
    Daemon -[#purple]> RDPD : Валидация stp_state_v/asic_state_v
    RDPD <-[#b4506e]> ASIC : Sync \n[asic_state_v]
    Daemon -[#0000FF]> Kernel : Установка сокетов для BPDU
    Daemon -[#purple]> RDPD : Оповещение [STPd_STATE_WORKING]
end

group#Gold Цикл рабочий
    Kernel -[#0000FF]> Daemon : Приём BPDU
    Daemon -[#green]/  Daemon : Обработка BPDU
    Netlink --[#df7000]> Daemon : Обновление состояний интерфейсов
    RDPD --[#purple]> Daemon : Обновление конфигурации
    Daemon -[#green]/ Daemon : Вычислениe состояний и переходов
    Daemon -[#purple]> RDPD : Установка stp_state_v/asic_state_v
    RDPD <-[#b4506e]> ASIC : Sync \n[asic_state_v]
    Daemon -[#0000FF]> Kernel : Отправка BPDU
end

group#Gold Цикл отладочный
    RDPD -[#purple]> Daemon : Сигнал [DEBUG_RESTART]
    Daemon -[#0000FF]> Kernel : Закрытие сокетов
    Daemon -[#purple]> RDPD : Оповещение [Power_OFF]
    RDPD <-[#b4506e]> ASIC : Sync \n[asic_state_v]
end

@enduml
